// <auto-generated />
using AspCepAPI.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspCepAPI.Migrations
{
    [DbContext(typeof(CepDomain))]
    partial class CepDomainModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("AspCepAPI.Models.CepModel", b =>
                {
                    b.Property<string>("cep")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("bairro");

                    b.Property<string>("complemento");

                    b.Property<string>("gia");

                    b.Property<string>("ibge");

                    b.Property<string>("localidade");

                    b.Property<string>("logradouro");

                    b.Property<string>("uf");

                    b.Property<string>("unidade");

                    b.HasKey("cep");

                    b.ToTable("CepModel");
                });
#pragma warning restore 612, 618
        }
    }
}
